insert into articulo (id, denominacion, preciounitario) values (1, 'Wine Decanter', 34.99);
insert into articulo (id, denominacion, preciounitario) values (2, 'Miso Dressing', 3.49);
insert into articulo (id, denominacion, preciounitario) values (3, 'Adjustable Laptop Stand', 29.99);
insert into articulo (id, denominacion, preciounitario) values (4, 'Portable Refrigerator Freezer', 299.99);
insert into articulo (id, denominacion, preciounitario) values (5, 'Garlic and Herb Rub', 2.29);
insert into articulo (id, denominacion, preciounitario) values (6, 'Under Desk Footrest', 29.99);
insert into articulo (id, denominacion, preciounitario) values (7, 'Ice Cube Tray with Lid', 10.99);
insert into articulo (id, denominacion, preciounitario) values (8, 'Mango Chunks', 4.89);
insert into articulo (id, denominacion, preciounitario) values (9, 'Organic Lentil Soup', 4.99);
insert into articulo (id, denominacion, preciounitario) values (10, 'Herbal Garden Starter Kit', 24.99);
insert into articulo (id, denominacion, preciounitario) values (11, 'Casual Long Cardigan', 45.99);
insert into articulo (id, denominacion, preciounitario) values (12, 'Cheesy Broccoli Soup Mix', 2.99);
insert into articulo (id, denominacion, preciounitario) values (13, 'Smartphone Photography Ring Light', 29.99);
insert into articulo (id, denominacion, preciounitario) values (14, 'Vegetable Sushi Rolls', 5.99);
insert into articulo (id, denominacion, preciounitario) values (15, 'Wrap Front Midi Skirt', 44.99);
insert into articulo (id, denominacion, preciounitario) values (16, 'Digital Food Thermometer', 19.99);
insert into articulo (id, denominacion, preciounitario) values (17, 'Digital Wireless Meat Thermometer', 39.99);
insert into articulo (id, denominacion, preciounitario) values (18, 'Chickpeas', 1.29);
insert into articulo (id, denominacion, preciounitario) values (19, 'LED Table Lamp', 29.99);
insert into articulo (id, denominacion, preciounitario) values (20, 'Buffalo Style Cauliflower Bites', 5.49);
insert into articulo (id, denominacion, preciounitario) values (21, 'Bicycle Repair Kit', 14.99);
insert into articulo (id, denominacion, preciounitario) values (22, 'Honey Butter Popcorn', 2.99);
insert into articulo (id, denominacion, preciounitario) values (23, 'Travel Hair Straightener', 29.99);
insert into articulo (id, denominacion, preciounitario) values (24, 'Lasagna Noodles', 1.89);
insert into articulo (id, denominacion, preciounitario) values (25, 'Electric Toothbrush', 49.95);
insert into articulo (id, denominacion, preciounitario) values (26, 'Plaid Flannel Shirt', 29.99);
insert into articulo (id, denominacion, preciounitario) values (27, 'Smartphone Gimbal', 89.99);
insert into articulo (id, denominacion, preciounitario) values (28, 'Multifunctional Baby Bottle Warmer', 39.99);
insert into articulo (id, denominacion, preciounitario) values (29, 'Stuffed Grape Leaves', 5.79);
insert into articulo (id, denominacion, preciounitario) values (30, 'Portable Water Filter', 29.99);
insert into articulo (id, denominacion, preciounitario) values (31, 'Frozen Vegetarian Pizza', 6.49);
insert into articulo (id, denominacion, preciounitario) values (32, 'Sweet Potato Mash', 3.99);
insert into articulo (id, denominacion, preciounitario) values (33, 'Red Lentils', 1.99);
insert into articulo (id, denominacion, preciounitario) values (34, 'Black Bean Salsa', 3.49);
insert into articulo (id, denominacion, preciounitario) values (35, 'Sweet Potato Fries', 3.99);
insert into articulo (id, denominacion, preciounitario) values (36, 'Noise-Canceling Headphones', 119.99);
insert into articulo (id, denominacion, preciounitario) values (37, 'Ribbed Knit Dress', 59.99);
insert into articulo (id, denominacion, preciounitario) values (38, 'Summer Tank Dress', 39.99);
insert into articulo (id, denominacion, preciounitario) values (39, 'Smartphone Photography Ring Light', 29.99);
insert into articulo (id, denominacion, preciounitario) values (40, 'Sunflower Seeds', 2.99);
insert into articulo (id, denominacion, preciounitario) values (41, 'Stainless Steel Travel Mug', 19.99);
insert into articulo (id, denominacion, preciounitario) values (42, 'Vegetarian Stuffed Peppers', 4.99);
insert into articulo (id, denominacion, preciounitario) values (43, 'Energy Bites', 3.99);
insert into articulo (id, denominacion, preciounitario) values (44, 'Flavored Instant Oatmeal', 2.99);
insert into articulo (id, denominacion, preciounitario) values (45, 'Inflatable Paddle Board', 349.99);
insert into articulo (id, denominacion, preciounitario) values (46, 'Laptop Sleeve', 24.99);
insert into articulo (id, denominacion, preciounitario) values (47, 'Portable Pet Pooper Scooper', 12.99);
insert into articulo (id, denominacion, preciounitario) values (48, 'Foldable Picnic Table', 49.99);
insert into articulo (id, denominacion, preciounitario) values (49, 'Honey Sesame Chicken', 8.99);
insert into articulo (id, denominacion, preciounitario) values (50, 'Jasmine Rice', 2.39);
