insert into cliente (id, nombre, direccion) values (1, 'Claudina Lutsch', '45 Summerview Alley');
insert into cliente (id, nombre, direccion) values (2, 'Dayna Goodman', '1 Leroy Hill');
insert into cliente (id, nombre, direccion) values (3, 'Lorene Wooffitt', '04416 Moose Parkway');
insert into cliente (id, nombre, direccion) values (4, 'Jeremy Abbot', '67 Russell Center');
insert into cliente (id, nombre, direccion) values (5, 'Christy Turbill', '2503 Pankratz Park');
insert into cliente (id, nombre, direccion) values (6, 'Rudolf Ruger', '927 Lake View Court');
insert into cliente (id, nombre, direccion) values (7, 'Averell Mitkin', '3 Maywood Road');
insert into cliente (id, nombre, direccion) values (8, 'Kippie Allerton', '807 Oriole Road');
insert into cliente (id, nombre, direccion) values (9, 'Robbin Trulocke', '7 Parkside Point');
insert into cliente (id, nombre, direccion) values (10, 'Myron Phlippi', '36642 Susan Park');
insert into cliente (id, nombre, direccion) values (11, 'Ardelle Janatka', '42 Butterfield Terrace');
insert into cliente (id, nombre, direccion) values (12, 'Rona Ferrari', '71 Spaight Court');
insert into cliente (id, nombre, direccion) values (13, 'Rikki Sherbrooke', '0919 Dottie Alley');
insert into cliente (id, nombre, direccion) values (14, 'Nadine Wickie', '298 Vera Park');
insert into cliente (id, nombre, direccion) values (15, 'Dodi Shovelbottom', '953 Fisk Terrace');
insert into cliente (id, nombre, direccion) values (16, 'Stephi Gaggen', '8 Nelson Drive');
insert into cliente (id, nombre, direccion) values (17, 'Pammie Eaves', '110 Magdeline Circle');
insert into cliente (id, nombre, direccion) values (18, 'Almira Tearney', '99 Killdeer Way');
insert into cliente (id, nombre, direccion) values (19, 'Lonni Rust', '30 Aberg Point');
insert into cliente (id, nombre, direccion) values (20, 'Constanta Frammingham', '7 Waxwing Road');
insert into cliente (id, nombre, direccion) values (21, 'Nollie Iron', '5 Cottonwood Pass');
insert into cliente (id, nombre, direccion) values (22, 'Jillene Coolahan', '0 Summer Ridge Place');
insert into cliente (id, nombre, direccion) values (23, 'Carmelia Parades', '0 Emmet Road');
insert into cliente (id, nombre, direccion) values (24, 'Thorpe Tresise', '0 Longview Lane');
insert into cliente (id, nombre, direccion) values (25, 'Klara Jermy', '0 Lindbergh Terrace');
insert into cliente (id, nombre, direccion) values (26, 'Ealasaid Bowmen', '6 Stang Point');
insert into cliente (id, nombre, direccion) values (27, 'Pippa Wilcot', '807 Delaware Junction');
insert into cliente (id, nombre, direccion) values (28, 'Rosalinda Petyt', '992 Dawn Way');
insert into cliente (id, nombre, direccion) values (29, 'Nanete Alten', '76876 Golden Leaf Road');
insert into cliente (id, nombre, direccion) values (30, 'Barnabe Crockford', '1910 Mitchell Place');
